### ISSUE TITLE
Inactive tracks and erroneous Solo and Mute reporting

### ISSUE THREAD

**Issue by SlauHalatyn** [rfiorentino1/Pro-Tools-Accessibility-Scripts#5]
When a track is inactive and shown in the Mix or Edit windows, the speak Soloed Tracks and Speak Muted Tracks scripts report the inactive tracks as being soloed and muted.

**Comment by ghost** [comment]
Confirm. Working on it.

**Comment by SlauHalatyn** [comment]
Oo, not sure but does replying to the email automatically add a comment to the issue on GitHub? That would be kind of cool in an automated kind of way :)
Slau

**Comment by ghost** [comment]
It does, and if I mentions issue number in my commit message, it tags it too!

**Comment by ghost** [comment]
If you want to mentions someone, use at sign before user name as one word, and if you want to mention another issue use number sign before the issue number. Let me know if this is fixed.

**Comment by SlauHalatyn** [comment]
Yep, OK problem solved. Squish!
:)
